<span style="font-size:larger;background:#333333;color:white">Diagonal Function</span><br>
<span style="font-size:medium;color:black">It is used to z the diagonal elements of an array, or, used to construct a new diagonal array</span><br>
<span style="font-size:medium;color:black">syntax:</span><br>
np.diag(a,k)

<span style="font-size:medium;color:black">Note:</span><br>
-If 'a' is a 2-D array,


In [40]:
#to import numpy library
import numpy as np

In [41]:
#creating a 2-D array of 3x3 
a = np.array([[1,2,3],[4,5,6],[1,2,3]])

In [42]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [43]:
#to check the dimension of array a
a.ndim

2

In [44]:
#extracting the diagonal elements of array 'a'
np.diag(a)

array([1, 5, 3])

In [45]:
#creating a 1-D array
a1 = np.array([1,2,4,5,6,6])

In [46]:
a1

array([1, 2, 4, 5, 6, 6])

In [47]:
#to check the dimension of array a1
a1.ndim

1

In [48]:
#constructing a 2-D diagonal array with elements of array a1
np.diag(a1)

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0],
       [0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 6]])

In [49]:
#creating a 2-D array of 3x3 
b = np.array([[1,2,3],[4,5,6],[1,2,3]])

In [50]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [51]:
#when k=0, it will consider the main diagonal
np.diag(b,k=0)

array([1, 5, 3])

In [52]:
#when k>0, it will consider the uppper diagonal 
np.diag(b,k=2)

array([3])

In [53]:
#when k<0, it will consider the lower diagonal 
np.diag(b,k=-2)

array([1])

In [54]:
#creating a 1-D array
b1 = np.array([1,2,4,5,6,6])

In [55]:
b1

array([1, 2, 4, 5, 6, 6])

In [56]:
#when k=0, it will consider the main diagonal
np.diag(b1,k=0)

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0],
       [0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 6]])

In [57]:
#when k>0, it will consider the uppper diagonal
np.diag(b1,k=2)

array([[0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 0, 6],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [58]:
#when k<0, it will consider the lower diagonal
np.diag(b1,k=-2)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0]])