<span style="font-size:larger ; background-color:#333333; color:white">Numpy - Full Array</span><br>
<span style="font-size:larger ; background-color:#333333; color:white">Full Array - An array in which all values are same(constant)</span>

<span style="font-size:medium; background-color:#333333; color:white">ZA = np.full(shape, fill_value)</span>

<span style="font-size:small; background-color:#333333; color:white">
- We can ddefine the shape, and pass the value to be  filled in the 'Full Array'.<br>
- We can create 1-D, 2-D, as well as 3-D Full Array, with integer, float or string values.<br>
- The default data-type is integer.
</span>


In [1]:
import numpy as np

In [2]:
#creating a Full Array, of 1 dimension, with 79 at each position
C1 = np.full(3,79)
print(C1)

[79 79 79]


In [3]:
#Creating a Full Array of 1 diension, with 79 and the data type as float.
C1 = np.full(3,79,dtype=float)
print(C1)

[79. 79. 79.]


In [4]:
#checking the type of C1
type(C1)

numpy.ndarray

In [5]:
#checking the dimension of C1
C1.ndim

1

In [6]:
#creating a full array, of 1 dimension with 99.9 at each position
C2 = np.full((2,3), 99.9)
print(C2)

[[99.9 99.9 99.9]
 [99.9 99.9 99.9]]


In [7]:
#creating a full array, of 2 dimension with data type as int 
C2 = np.full((2,3), 99.9, dtype=int)
print(C2)

[[99 99 99]
 [99 99 99]]


In [8]:
#creating a full array of 2 dimension with data type as string 
C2 = np.full((2,3), 99.9, dtype=str)
print(C2)

[['9' '9' '9']
 ['9' '9' '9']]


In [9]:
#checking the shape of 'C2'
C2.shape

(2, 3)

In [10]:
#creating a full array with string datatype, of 3 dimensions with "python" at each position
C3 = np.full((2,3,4), 'python')
print(C3)

[[['python' 'python' 'python' 'python']
  ['python' 'python' 'python' 'python']
  ['python' 'python' 'python' 'python']]

 [['python' 'python' 'python' 'python']
  ['python' 'python' 'python' 'python']
  ['python' 'python' 'python' 'python']]]


In [11]:
C3.size

24

In [13]:
#checking the dimension of C3, with new method. 
np.ndim(C3)

3