<span style="font-size:larger; background-color:#333333; color:white">Numpy Basics</span> 

<span style="font-size:small; background-color:#333333; color:white">
1. Array <br>
2. Array Attributes - Shape, Reshape, Size, Dimension, Dtype. <br>
3. 1-D Array <br>
4. 2-D Array <br>
5. 3-D Array <br>
6. Zeros Array <br>
7. Ones Array <br>
8. Full Array <br>
9. Random Function <br>
10. Linspace Function <br>
</span>

In [3]:
#importing Numpy.
import numpy as np

<span style="font-size:larger; background-color:#333333; color:white">Numpy Arrays: 1-D, 2-D, 3-D Arrays</span>

In [2]:
# Create a NumPy array named A1 containing the elements.
A1 = np.array([1,2,3,4,5])

In [3]:
#print the Numpy array.
print(A1)

[1 2 3 4 5]


In [4]:
#Check the type of the variable A1.
type(A1) 

numpy.ndarray

In [5]:
#check the shape of the variable A1.
A1.shape

(5,)

In [6]:
#check the size of the variable A1.
A1.size

5

In [7]:
#Create a NumPy array named A2 containing a 2D array with two rows and four columns.
A2 = np.array([[1,3,4,5], [1,2,4,5,]])

In [8]:
#Check the number of dimensions of the NumPy array A2.
A2.ndim

2

In [9]:
#check the size of the variable A2.
A2.size

8

In [10]:
#Create a NumPy array named A3 containing a 3D array with two rows and four columns.
A3 = np.array([[[2,3,4], [2,3,4], [3,4,5]]])

In [11]:
#print the Numpy array.
print(A3)

[[[2 3 4]
  [2 3 4]
  [3 4 5]]]


In [12]:
#check the size of the variable A3.
A3.size

9

In [13]:
#check the size of the variable A3.
A3.shape

(1, 3, 3)

In [14]:
#check the type of the variabe A3.
type(A3)

numpy.ndarray

<span style="font-size:larger ; background-color:#333333; color:white">Numpy - Zeros Array</span>

<span style="font-size:medium; background-color:#333333; color:white">ZA = np.zeros(shape, dtype)</span>

<span style="font-size:small; background-color:#333333; color:white">
- We can define the shape and data-type of zeros array..<br>
- We can create 1-D, 2-D, as well as 3-D zeros array.<br>
- The default data-type is float.
</span>


In [50]:
# Create a zeros array of 1 dimension.
Z1 = np.zeros(3)    
Z1

array([0., 0., 0.])

In [52]:
#Create a zeros array of 1 dimension with data type as intgeger.
Z2 = np.zeros(15, dtype = int)
Z2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
#check the type.
type(Z2)

numpy.ndarray

In [54]:
#check the dimension.
np.ndim(Z2)

1

In [64]:
#create a zeros array of 2 dimensions
Z3 = np.zeros((3,4))
Z3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
#create a zeros arrayof 2 dimensions.
Z4 = np.zeros((3,4), dtype=int)
Z4

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [78]:
#check the shape 
Z4.shape

(3, 4)

In [71]:
#create a zeros array of 3 dimensions.
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [82]:
#create a zeros array of 3 dimensions with data type as integer.
Z5 = np.zeros((3,3,3), dtype=int)
Z5

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [83]:
#check the dimensions
Z5.ndim

3

In [84]:
#check the size 
Z5.size

27

<span style="font-size:larger ; background-color:#333333; color:white">Numpy - Ones Array</span>

<span style="font-size:medium; background-color:#333333; color:white">ZA = np.Ones(shape, dtype)</span>

<span style="font-size:small; background-color:#333333; color:white">
- We can define the shape and data-type of zeros array..<br>
- We can create 1-D, 2-D, as well as 3-D zeros array.<br>
- The default data-type is float.
</span>


In [88]:
# Create a Ones array of 1 dimension.
B1 = np.ones(3)    
B1

array([1., 1., 1.])

In [91]:
#Create a Ones array of 1 dimension with data type as intgeger.
B2 = np.ones(5, dtype = int)
B2

array([1, 1, 1, 1, 1])

In [90]:
#check the type.
type(B2)

numpy.ndarray

In [92]:
#check the dimension.
np.ndim(B2)

1

In [94]:
#create a Ones array of 2 dimensions
B3 = np.ones((3,4))
B3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [95]:
#create a Ones arrayof 2 dimensions.
B4 = np.ones((3,4), dtype=int)
B4

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [96]:
#check the shape 
B4.shape

(3, 4)

In [101]:
#create a Ones array of 3 dimensions.
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [100]:
#create a Ones array of 3 dimensions with data type as integer.
B5 = np.ones((3,3,3), dtype=int)
B5

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [102]:
#check the dimensions
B5.ndim

3

In [103]:
#check the size 
B5.size

27

<span style="font-size:larger ; background-color:#333333; color:white">Numpy - Full Array</span><br>
<span style="font-size:larger ; background-color:#333333; color:white">Full Array - An array in which all values are same(constant)</span>

<span style="font-size:medium; background-color:#333333; color:white">ZA = np.full(shape, fill_value)</span>

<span style="font-size:small; background-color:#333333; color:white">
- We can ddefine the shape, and pass the value to be  filled in the 'Full Array'.<br>
- We can create 1-D, 2-D, as well as 3-D Full Array, with integer, float or string values.<br>
- The default data-type is integer.
</span>


In [25]:
#creating a Full Array, of 1 dimension, with 79 at each position

C1 = np.full(3,79)
print(C1)


[79 79 79]


In [26]:
#Creating a Full Array of 1 diension, with 79 and the data type as float.
C1 = np.full(3,79,dtype=float)
print(C1)

[79. 79. 79.]


In [29]:
#checking the type of C1
type(C1)

numpy.ndarray

In [30]:
#checking the dimension of C1
C1.ndim

1

In [34]:
#creating a full array, of 1 dimension with 99.9 at each position
C2 = np.full((2,3), 99.9)
print(C2)

[[99.9 99.9 99.9]
 [99.9 99.9 99.9]]


In [35]:
#creating a full array, of 2 dimension with data type as int 
C2 = np.full((2,3), 99.9, dtype=int)
print(C2)

[[99 99 99]
 [99 99 99]]


In [37]:
#creating a full array of 2 dimension with data type as string 
C2 = np.full((2,3), 99.9, dtype=str)
print(C2)

[['9' '9' '9']
 ['9' '9' '9']]


In [38]:
#checking the shape of 'C2'
C2.shape

(2, 3)

In [46]:
#creating a full array with string datatype, of 3 dimensions with "python" at each position

C3 = np.full((2,3,4), 'python')
print(C3)

[[['python' 'python' 'python' 'python']
  ['python' 'python' 'python' 'python']
  ['python' 'python' 'python' 'python']]

 [['python' 'python' 'python' 'python']
  ['python' 'python' 'python' 'python']
  ['python' 'python' 'python' 'python']]]


In [51]:
#checking the dimension of C3, with new method. 
np.ndim(C3)

3

In [54]:
C3.size

24

<span style="font-size:larger ; background-color:#333333; color:white">The Random Module contain the function which are used for generating random numbers.</span><br>


In [56]:
#importing the numpy library
import numpy as np

In [55]:
#from numpy library, importing the random module 
from numpy import random

<span style="font-size:larger ;  color:black">1. Random Function</span><br>
It returns random float number(s) between 0 and 1.

In [73]:
np.random.random()

0.890743225050126

In [77]:
np.random.random(4)

array([0.12058427, 0.08957807, 0.62061146, 0.1349687 ])

In [79]:
np.random.random((2,3))

array([[0.8778371 , 0.9475572 , 0.61556616],
       [0.137471  , 0.52102531, 0.16051855]])

In [82]:
random.random(((3,3,3)))

array([[[0.16088569, 0.96920002, 0.12048066],
        [0.71061159, 0.22302433, 0.92465405],
        [0.00568583, 0.68615664, 0.77792677]],

       [[0.35513371, 0.0293275 , 0.68566253],
        [0.29049756, 0.33886332, 0.97829429],
        [0.98946014, 0.14615963, 0.64101583]],

       [[0.82866432, 0.2056226 , 0.3392275 ],
        [0.6710358 , 0.0799861 , 0.85850466],
        [0.04816045, 0.69036576, 0.90555153]]])

In [84]:
random.random((3,3,3))

array([[[0.39979783, 0.16279539, 0.62566832],
        [0.80841686, 0.38468527, 0.5693477 ],
        [0.56185945, 0.73655012, 0.17686432]],

       [[0.87160286, 0.58185986, 0.10635048],
        [0.86935772, 0.06860758, 0.84216047],
        [0.38686431, 0.0809544 , 0.80534535]],

       [[0.0821053 , 0.48646732, 0.16613098],
        [0.41894811, 0.42349232, 0.2093576 ],
        [0.20738074, 0.86467868, 0.37934593]]])