<span style="font-size:larger; background-color:#333333; color:white">Numpy Basics</span> 

<span style="font-size:small; background-color:#333333; color:white">
1. Array <br>
2. Array Attributes - Shape, Reshape, Size, Dimension, Dtype. <br>
3. 1-D Array <br>
4. 2-D Array <br>
5. 3-D Array <br>
6. Zeros Array <br>
7. Ones Array <br>
8. Full Array <br>
9. Random Function <br>
10. Linspace Function <br>
</span>

In [3]:
#importing Numpy.
import numpy as np

<span style="font-size:larger; background-color:#333333; color:white">Numpy Arrays: 1-D, 2-D, 3-D Arrays</span>

In [2]:
# Create a NumPy array named A1 containing the elements.
A1 = np.array([1,2,3,4,5])

In [3]:
#print the Numpy array.
print(A1)

[1 2 3 4 5]


In [4]:
#Check the type of the variable A1.
type(A1) 

numpy.ndarray

In [5]:
#check the shape of the variable A1.
A1.shape

(5,)

In [6]:
#check the size of the variable A1.
A1.size

5

In [7]:
#Create a NumPy array named A2 containing a 2D array with two rows and four columns.
A2 = np.array([[1,3,4,5], [1,2,4,5,]])

In [8]:
#Check the number of dimensions of the NumPy array A2.
A2.ndim

2

In [9]:
#check the size of the variable A2.
A2.size

8

In [10]:
#Create a NumPy array named A3 containing a 3D array with two rows and four columns.
A3 = np.array([[[2,3,4], [2,3,4], [3,4,5]]])

In [11]:
#print the Numpy array.
print(A3)

[[[2 3 4]
  [2 3 4]
  [3 4 5]]]


In [12]:
#check the size of the variable A3.
A3.size

9

In [13]:
#check the size of the variable A3.
A3.shape

(1, 3, 3)

In [14]:
#check the type of the variabe A3.
type(A3)

numpy.ndarray

---------------------------------------------------------------------------------------------------------------------------------------------

In [2]:
#importing the numpy library
import numpy as np

In [3]:
#from numpy library, importing the random module 
from numpy import random

<span style="font-size:larger ;  color:black">1. Random Function</span><br>
It returns random float number(s) between 0 and 1.

In [73]:
np.random.random()

0.890743225050126

In [77]:
np.random.random(4)

array([0.12058427, 0.08957807, 0.62061146, 0.1349687 ])

In [79]:
np.random.random((2,3))

array([[0.8778371 , 0.9475572 , 0.61556616],
       [0.137471  , 0.52102531, 0.16051855]])

random.random(((3,3,3)))

In [4]:
random.random((2,3,5))

array([[[0.9494507 , 0.11600265, 0.05387388, 0.20251036, 0.03959577],
        [0.00896619, 0.55698511, 0.43870684, 0.47477408, 0.82639191],
        [0.76351873, 0.75894225, 0.41189692, 0.53669228, 0.19490883]],

       [[0.84558864, 0.4080591 , 0.27108785, 0.61881349, 0.067901  ],
        [0.68815087, 0.05687113, 0.34810072, 0.96626304, 0.72583748],
        [0.16513146, 0.8763876 , 0.86803267, 0.98284902, 0.5486939 ]]])

---------------------------------------------------------------------------------------------------------------------------------------------

<span style="font-size:larger ;  color:black">2. Randint Function</span><br>
-It generates random integer numbers between given range. <br>
-By default, the range starts from 0.<br>
-The numbers can repeat.

In [9]:
random.randint(2,13)

6

In [14]:
random.randint(2,20,5)

array([13, 13,  8, 16,  8])

In [16]:
random.randint(4)

2

---------------------------------------------------------------------------------------------------------------------------------------------

<span style='font-size:larger ; color:black'>3. Rand Function </span><br>
It returns random floar numbers between 0 and 1

In [22]:
random.rand()

0.902079472614698

In [23]:
np.random.rand(4)

array([0.2913952 , 0.65915336, 0.83081173, 0.75047717])

In [24]:
random.rand(2,3)

array([[0.98409065, 0.76771711, 0.7844836 ],
       [0.30141106, 0.01738509, 0.96454336]])

In [25]:
random.rand(2,3,5)

array([[[0.1453006 , 0.23685648, 0.86803028, 0.17458674, 0.89210906],
        [0.59260807, 0.73637715, 0.87538061, 0.1075027 , 0.5821254 ],
        [0.70517858, 0.17976635, 0.59172474, 0.92271914, 0.70277193]],

       [[0.94701399, 0.74759603, 0.30584265, 0.90300277, 0.74969341],
        [0.34943254, 0.43254502, 0.4320307 , 0.5995874 , 0.95076259],
        [0.32976877, 0.52159125, 0.57150815, 0.4043727 , 0.88883577]]])

---------------------------------------------------------------------------------------------------------------------------------------------

<span style='font-size:larger ; color:black'>4. Randn Function </span><br>
It returns random float numbers (Positive and negative both) in the form of array.

In [10]:
random.randn()

1.0117858104924193

random.randn(4)

In [12]:
random.randn(3,5)

array([[-1.20069145, -0.03472116,  0.22668206,  1.4916043 ,  1.63323661],
       [ 0.43315079, -1.11374784,  0.88312598,  0.19682902,  2.24461767],
       [ 0.28102145, -0.35503167, -0.64658351, -0.35863829, -1.03521524]])

random.randn(4,2,3)

---------------------------------------------------------------------------------------------------------------------------------------------

<span style='font-size:larger ; color:black'> 5.Uniform Function </span><br>
-It returns random float numbers between the given range of values.<br>
-The random numbers can't repeat.<br> 
-By default, the range starts from 0.<br>
-If nothing is passed in ().it will return a float number between 0 and 1.

In [25]:
np.random.uniform(3,6)

5.333453849844753

In [26]:
np.random.uniform(3,4,17)

array([3.55455217, 3.19668035, 3.8593357 , 3.53295096, 3.37352863,
       3.99365474, 3.27809816, 3.26399556, 3.77859439, 3.85974414,
       3.57660044, 3.05903182, 3.19358436, 3.45347234, 3.19584345,
       3.5496284 , 3.17516816])

In [27]:
np.random.uniform(5)

2.0557173244258675

---------------------------------------------------------------------------------------------------------------------------------------------

<span style='font-size:larger; color:black'>6.Choice Function </span><br>
-It returns random integer numbers from the given sequence.<br>
-The range starts from 0 by default.<br>
-If only 1 element is passed, then it will return a number between 0 and that element.<br>
-By defult, replace=True, which means the number can repeat.

In [28]:
np.random.choice([2,5,3,5,6,67,75,5,55])

3

In [30]:
np.random.choice([2,5,3,5,6,67,75,5,55],2)

array([5, 2])

In [34]:
np.random.choice(10,5)

array([3, 0, 1, 4, 8])

In [35]:
np.random.choice(12)

4

In [38]:
np.random.choice([2,5,3,5,6,67,75,5,55],size=5)

array([ 5,  6,  2,  2, 75])

In [45]:
np.random.choice([2,5,3,5,6,67,75,5,55],size=5, replace=False)

array([ 6, 55,  5,  3, 67])

---------------------------------------------------------------------------------------------------------------------------------------------

<span style='font-size:larger; color:black'>7. Linspace Function </span><br>
-Linspace Function return evenly linear spaced values within a given interval<br>
-Note by deafult it shows 50 values<br>
<span style="font-size:larger ; color:black">
np.linspace(start_value, stop_value, num=50, endpoint= False, retstep=True,dtype=None) </span>

In [56]:
N = np.linspace(2, 20, num=10 )

print(N)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [57]:
N1 = np.linspace(2,20, num=10, endpoint=False)
print(N1)

[ 2.   3.8  5.6  7.4  9.2 11.  12.8 14.6 16.4 18.2]


In [67]:
N2 = np.linspace(2,20, num=10, endpoint=False)
print(N2)

[ 2.   3.8  5.6  7.4  9.2 11.  12.8 14.6 16.4 18.2]


In [68]:
N3 = np.linspace(2,20, num=10, endpoint=True, retstep = True)
print(N3)

(array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.]), 2.0)


In [74]:
N4 = np.linspace(2,20, num=10, endpoint=True, retstep=True, dtype=str)
print(N4)

(array(['2.0', '4.0', '6.0', '8.0', '10.0', '12.0', '14.0', '16.0', '18.0',
       '20.0'], dtype='<U32'), 2.0)


---------------------------------------------------------------------------------------------------------------------------------------------

<span style='font-size:larger;background-color:#333333; color:white'> Empty Function</span><br>
<span style='font-size:larger'>syntax: np.empty(shape.dtype)</span><br>
-Shape can give in list or tuple form <br>
-The default datatype is float 