<span style="font-size:larger; background-color:#333333; color:white">Numpy Basics: 1-D, 2-D, 3-D Arrays</span><br>
<span style="font-size:medium; background-color:#333333; color:white">Numpy Arrays: 1-D, 2-D, 3-D Arrays</span>

In [3]:
#importing Numpy.
import numpy as np

In [4]:
# Create a NumPy array named A1 containing the elements.
A1 = np.array([1,2,3,4,5])

In [5]:
#print the Numpy array.
print(A1)

[1 2 3 4 5]


In [6]:
#Check the type of the variable A1.
type(A1) 

numpy.ndarray

In [7]:
#check the shape of the variable A1.
A1.shape

(5,)

In [8]:
#check the size of the variable A1.
A1.size

5

In [9]:
#Create a NumPy array named A2 containing a 2D array with two rows and four columns.
A2 = np.array([[1,3,4,5], [1,2,4,5,]])

In [10]:
#Check the number of dimensions of the NumPy array A2.
A2.ndim

2

In [11]:
#check the size of the variable A2.
A2.size

8

In [12]:
#Create a NumPy array named A3 containing a 3D array with two rows and four columns.
A3 = np.array([[[2,3,4], [2,3,4], [3,4,5]]])

In [13]:
#print the Numpy array.
print(A3)

[[[2 3 4]
  [2 3 4]
  [3 4 5]]]


In [14]:
#check the size of the variable A3.
A3.size

9

In [15]:
#check the size of the variable A3.
A3.shape

(1, 3, 3)

In [16]:
#check the type of the variabe A3.
type(A3)

numpy.ndarray