<span style="font-size:larger ; background-color:#333333; color:white">Numpy - Ones Array</span>

<span style="font-size:medium; background-color:#333333; color:white">ZA = np.Ones(shape, dtype)</span>

<span style="font-size:small; background-color:#333333; color:white">
- We can define the shape and data-type of zeros array..<br>
- We can create 1-D, 2-D, as well as 3-D zeros array.<br>
- The default data-type is float.
</span>


In [34]:
import numpy as np

In [35]:
# Create a ones array of 1 dimension.
Z1 = np.ones(3)    
Z1

array([1., 1., 1.])

In [36]:
#Create a ones array of 1 dimension with data type as intgeger.
Z2 = np.ones(15, dtype = int)
Z2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [37]:
#check the type.
type(Z2)

numpy.ndarray

In [38]:
#check the dimension.
np.ndim(Z2)

1

In [39]:
#create a ones array of 2 dimensions
Z3 = np.ones((3,4))
Z3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
#create a ones arrayof 2 dimensions.
Z4 = np.ones((3,4), dtype=int)
Z4

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [41]:
#check the shape 
Z4.shape

(3, 4)

In [42]:
#create a ones array of 3 dimensions.
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [43]:
#create a ones array of 3 dimensions with data type as integer.
Z5 = np.ones((3,3,3), dtype=int)
Z5

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [44]:
#check the dimensions
Z5.ndim

3

In [45]:
#check the size 
Z5.size

27