<span style="font-size:larger ; background-color:#333333; color:white">Random Module</span><br>
<span style='font-size:small; background-color:#333333; color:white'>-random module contain the function which are used for generating random numbers.</span>

In [34]:
#importing the numpy library
import numpy as np

In [35]:
#from numpy library, importing the random module 
from numpy import random

<span style="font-size:larger ;  color:black">1. Random Function</span><br>
It returns random float number(s) between 0 and 1.

In [36]:
np.random.random()

0.7326367378036437

In [37]:
np.random.random(4)

array([0.99150231, 0.71854431, 0.00655163, 0.81194438])

In [38]:
np.random.random((2,3))

array([[0.96197269, 0.04371433, 0.47475187],
       [0.20796391, 0.02649573, 0.28614836]])

In [39]:
random.random(((3,3,3)))

array([[[0.25690737, 0.38459285, 0.12567247],
        [0.65074711, 0.50563664, 0.58469037],
        [0.06987279, 0.83964412, 0.46156504]],

       [[0.26786742, 0.62344036, 0.28216714],
        [0.5198229 , 0.30351804, 0.75849188],
        [0.53160223, 0.34129627, 0.12204524]],

       [[0.27413408, 0.19990364, 0.29824398],
        [0.01299008, 0.63193204, 0.23138706],
        [0.9727004 , 0.63197136, 0.95490215]]])

In [40]:
random.random((2,3,5))

array([[[0.32425086, 0.62132312, 0.64156401, 0.36156064, 0.81130667],
        [0.01022639, 0.40298775, 0.49429751, 0.72147882, 0.8446614 ],
        [0.5290065 , 0.79122366, 0.12365645, 0.91228068, 0.5823371 ]],

       [[0.30728804, 0.7528439 , 0.86346215, 0.52382872, 0.90735895],
        [0.99270522, 0.27520938, 0.12033787, 0.26457255, 0.44676408],
        [0.71757662, 0.10770792, 0.19424871, 0.71106461, 0.48371708]]])

<span style="font-size:larger ;  color:black">2. Randint Function</span><br>
-It generates random integer numbers between given range. <br>
-By default, the range starts from 0.<br>
-The numbers can repeat.

In [41]:
random.randint(2,13)

11

In [42]:
random.randint(2,20,5)

array([ 8,  6, 13,  6,  9])

In [43]:
random.randint(4)

1

<span style='font-size:larger ; color:black'>3. Rand Function </span><br>
It returns random floar numbers between 0 and 1

In [44]:
random.rand()

0.16626382173374477

In [45]:
np.random.rand(4)

array([0.61011932, 0.37367438, 0.40043977, 0.22341946])

In [46]:
random.rand(2,3)

array([[0.32198163, 0.99189652, 0.32716964],
       [0.48508448, 0.31883439, 0.58188479]])

In [47]:
random.rand(2,3,5)

array([[[0.52490514, 0.28334626, 0.15102944, 0.22713234, 0.92564764],
        [0.58902266, 0.67940078, 0.80746542, 0.72827334, 0.54638192],
        [0.50246489, 0.77269383, 0.547659  , 0.47193425, 0.63285903]],

       [[0.77556946, 0.10717074, 0.75045652, 0.23391043, 0.28080576],
        [0.63985147, 0.91024501, 0.94817799, 0.72264366, 0.89152861],
        [0.33720147, 0.74244895, 0.09295806, 0.81149528, 0.43039937]]])

<span style='font-size:larger ; color:black'>4. Randn Function </span><br>
It returns random float numbers (Positive and negative both) in the form of array.

In [48]:
random.randn(4,2,3)

array([[[-0.78261858,  1.62369414, -0.89368988],
        [ 3.59727546, -0.10072507, -1.58721605]],

       [[ 0.1266367 ,  1.48203215, -0.50826379],
        [ 0.21507498, -0.2600439 , -1.18142037]],

       [[-0.12668983,  1.67095743,  1.90766086],
        [ 0.16331341,  0.39574965, -0.2274875 ]],

       [[ 0.29626017, -0.30850495,  0.19599564],
        [ 0.90721567, -2.37416665,  2.07457182]]])

In [49]:
random.randn(4)

array([ 0.18648803, -1.33487682,  0.5053688 ,  0.30859223])

In [50]:
random.randn()

0.4596682039082476

In [51]:
random.randn(3,5)

array([[ 1.48703925, -0.36980239,  0.69176332,  1.91527656, -0.43419327],
       [-2.03666491,  1.22020739, -0.69432567,  0.25498552, -0.53839797],
       [-0.13863812, -0.75638913, -2.05204621, -0.96557783, -1.27892238]])

<span style='font-size:larger ; color:black'> 5.Uniform Function </span><br>
-It returns random float numbers between the given range of values.<br>
-The random numbers can't repeat.<br> 
-By default, the range starts from 0.<br>
-If nothing is passed in ().it will return a float number between 0 and 1.

In [52]:
np.random.uniform(3,6)

4.151126929805198

In [53]:
np.random.uniform(3,4,17)

array([3.425738  , 3.60112422, 3.57861508, 3.19316542, 3.50119386,
       3.04733609, 3.13289633, 3.07015408, 3.48412807, 3.79894956,
       3.72664546, 3.63744821, 3.68217395, 3.19045733, 3.2041137 ,
       3.49785645, 3.97301287])

In [54]:
np.random.uniform(5)

2.830108729239069

<span style='font-size:larger; color:black'>6.Choice Function </span><br>
-It returns random integer numbers from the given sequence.<br>
-The range starts from 0 by default.<br>
-If only 1 element is passed, then it will return a number between 0 and that element.<br>
-By defult, replace=True, which means the number can repeat.

In [55]:
np.random.choice([2,5,3,5,6,67,75,5,55])

5

In [56]:
np.random.choice(10,5)

array([1, 9, 4, 9, 5])

In [57]:
np.random.choice(12)

7

In [58]:
np.random.choice([2,5,3,5,6,67,75,5,55],size=5)

array([ 5,  5, 75, 55, 55])

In [59]:
np.random.choice([2,5,3,5,6,67,75,5,55],size=5, replace=False)

array([3, 6, 5, 5, 5])

<span style='font-size:larger; color:black'>7. Linspace Function </span><br>
-Linspace Function return evenly linear spaced values within a given interval<br>
-Note by deafult it shows 50 values<br>
<span style="font-size:larger ; color:black">
np.linspace(start_value, stop_value, num=50, endpoint= False, retstep=True,dtype=None) </span>

In [60]:
N = np.linspace(2, 20, num=10 )
print(N)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [61]:
N1 = np.linspace(2,20, num=10, endpoint=False)
print(N1)

[ 2.   3.8  5.6  7.4  9.2 11.  12.8 14.6 16.4 18.2]


In [62]:
N2 = np.linspace(2,20, num=10, endpoint=False)
print(N2)

[ 2.   3.8  5.6  7.4  9.2 11.  12.8 14.6 16.4 18.2]


In [63]:
N3 = np.linspace(2,20, num=10, endpoint=True, retstep = True)
print(N3)

(array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.]), 2.0)


In [64]:
N4 = np.linspace(2,20, num=10, endpoint=True, retstep=True, dtype=str)
print(N4)

(array(['2.0', '4.0', '6.0', '8.0', '10.0', '12.0', '14.0', '16.0', '18.0',
       '20.0'], dtype='<U32'), 2.0)
