<span style='font-size:larger; background:#333333; color:white'>Transpose Function </span><br>
<span style='font-size:larger'>syntax</span><br>
<span styl='font-size:medium'>array.T&nbsp;&nbsp;(or)&nbsp;&nbsp;np.transpose(array))</span><br>
-It converts the Rows into Columns, and Columns into Rows


In [48]:
#to import numpy library
import numpy as np

<span style='font-size:larger'>Transpose of a 2-D array</span><br>

In [49]:
#creating a 2-D array of 2x3
a = np.array([[2,4,3],[1,2,3]])

In [50]:
a

array([[2, 4, 3],
       [1, 2, 3]])

In [51]:
#transpose of array a
b = a.T

In [52]:
#checking the original shape of a 
a.shape

(2, 3)

In [53]:
#checking the shape of a after transpose 
b.shape

(3, 2)

In [54]:
#alternate command to transpose
np.transpose(a)

array([[2, 1],
       [4, 2],
       [3, 3]])

---

<span style='font-size:larger'>Transpose of a 1-D array</span><br>

In [55]:
#creating a 1-D array of 6 elements 
d = np.array([1,2,3,4,5,6])

In [56]:
d

array([1, 2, 3, 4, 5, 6])

In [57]:
#transpose of array 'd'
d.T

array([1, 2, 3, 4, 5, 6])

In [58]:
#checking the original shape of 'd'
d.shape

(6,)

In [59]:
d.T.shape

(6,)

---

<span style='font-size:larger'>Transpose of a 3-D array</span><br>

In [60]:
#creating a 3-D arrray of 1x3x3 element
e = np.array([[[1,2,3],[2,3,4],[4,5,6]]])

In [61]:
e

array([[[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]]])

In [62]:
#transpose of array 'e'
e.T

array([[[1],
        [2],
        [4]],

       [[2],
        [3],
        [5]],

       [[3],
        [4],
        [6]]])

In [63]:
#checking the original shape of 'e'
e.shape

(1, 3, 3)

In [64]:
#checking the shape of 'e' after transpose
e.T.shape

(3, 3, 1)

---