<span style="font-size:larger;background:#333333;color:white">Unary Operators</span><br>
<span style="font-size:medium;color:black">Those operators that require only one operand.</span><br>
These functions can be applied row-wise or column-wise by setting an 'axis' parameter

<span style="font-size:medium;color:black">supose 'a' is an array
</span><br>
<span style="font-size:small;color:black">a.max(), a.max(axis=1), a.max(axis=0) a.sum()<br>
a.min(), a.min(axis=1), a.min(axis=0), np.sum(a, axis=1)
</span><br>

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
a.max()

4

In [6]:
a.min()

1

In [7]:
a.sum()

10

In [18]:
b = np.array([[23,23,56],[66,55,44],])

In [21]:
b

array([[23, 23, 56],
       [66, 55, 44]])

In [19]:
b.max(axis=1)

array([56, 66])

In [20]:
b.max(axis=0)

array([66, 55, 56])

In [22]:
b.min()

23

In [24]:
b.min(axis=1)

array([23, 44])

In [25]:
b.min(axis=0)

array([23, 23, 44])

In [26]:
b.sum()

267

In [27]:
b.sum(axis=1)

array([102, 165])

In [28]:
b.sum(axis=0)

array([ 89,  78, 100])

In [34]:
c = np.arange(18).reshape(2,3,3)

In [35]:
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [36]:
c.max()

17

In [37]:
c.min()

0

In [38]:
c.max(axis=1)

array([[ 6,  7,  8],
       [15, 16, 17]])

In [39]:
c.min(axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
c.sum()

153

In [42]:
c.sum(axis=1)

array([[ 9, 12, 15],
       [36, 39, 42]])

---