<span style="font-size:larger;background:#333333;color:white">Vstack & Hstack-Numpy</span><br>
-Vstack-Combine the arrays vertically.<br>
-Hstack-Combine the array horizontally.

In [75]:
import numpy as np

<span style='font-size:medium'>1-D Array

In [76]:
a = np.array([1,2,3,34,4])

In [77]:
b = np.array([9,8,7,6,5])

In [78]:
np.vstack((a,b))

array([[ 1,  2,  3, 34,  4],
       [ 9,  8,  7,  6,  5]])

In [79]:
np.hstack((a,b))

array([ 1,  2,  3, 34,  4,  9,  8,  7,  6,  5])

<span style='font-size:medium'>2-D Array

In [80]:
p = np.array([[1,2,3,4,4],[2,3,4,5,5]])

In [81]:
p

array([[1, 2, 3, 4, 4],
       [2, 3, 4, 5, 5]])

In [82]:
q = np.array([[2,3,4,54,5],[4,3,5,'d',36]])

In [83]:
q

array([['2', '3', '4', '54', '5'],
       ['4', '3', '5', 'd', '36']], dtype='<U21')

In [84]:
np.vstack((p,q))

array([['1', '2', '3', '4', '4'],
       ['2', '3', '4', '5', '5'],
       ['2', '3', '4', '54', '5'],
       ['4', '3', '5', 'd', '36']], dtype='<U21')

In [85]:
np.hstack((p,q))

array([['1', '2', '3', '4', '4', '2', '3', '4', '54', '5'],
       ['2', '3', '4', '5', '5', '4', '3', '5', 'd', '36']], dtype='<U21')

<span style='font-size:medium'>3-D Array

In [86]:
x = np.array([[[2,3,4],[2,3,54],[33,7,7]]])

In [87]:
y = np.array([[[5,6,7],[56,75,43],[44,4,23]]])

In [88]:
x

array([[[ 2,  3,  4],
        [ 2,  3, 54],
        [33,  7,  7]]])

In [89]:
y

array([[[ 5,  6,  7],
        [56, 75, 43],
        [44,  4, 23]]])

In [90]:
x1 = np.vstack((x,y))
print(x1)

[[[ 2  3  4]
  [ 2  3 54]
  [33  7  7]]

 [[ 5  6  7]
  [56 75 43]
  [44  4 23]]]


In [91]:
y1 = np.hstack((x,y))
print(y1)

[[[ 2  3  4]
  [ 2  3 54]
  [33  7  7]
  [ 5  6  7]
  [56 75 43]
  [44  4 23]]]


In [92]:
x1.shape

(2, 3, 3)

In [93]:
y1.shape

(1, 6, 3)