<span style='font-size:larger'>Zeros like, Ones like, Full like Array</span><br>

In [56]:
#to import Numpy library
import numpy as np

In [57]:
#to import random module from numpy library
from numpy import random

<span style='font-size:medium;background:#333333; color:white'>Ones Like array</span><br>

<span style='font-size:medium'>Ones Like Array - it returns an array of ones, with same shape & type as of the given array.</span><br>
<span stype='font-size:medium'>Syntax:</span><br>
np.ones_like(array,dtype)<br>

In [58]:
#creating a 1-D array
a = np.array([21,52,93])

In [59]:
#creating an ones array, from array a
b = np.ones_like(a)

In [60]:
b

array([1, 1, 1])

In [61]:
#creating a 2-D Random array of shape 3x4
a1 = np.random.random((3,4))

In [62]:
a1

array([[0.28028715, 0.01911937, 0.02783875, 0.72373474],
       [0.23812294, 0.72036431, 0.08829727, 0.36447823],
       [0.16218269, 0.21545772, 0.55087399, 0.51638094]])

In [63]:
#creating an ones array, from array a1
b2 = np.ones_like(a1)

In [64]:
b2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [65]:
#creating an Ones array of integer datatype, from array a1
b3 = np.ones_like(a1,dtype=int)

In [66]:
b3

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

--------------------------------------------------------------------------------------------------------------------------

<span style ='font-size:medium'>Zeros Like Array- It returns an array of zeros, with the same shape & type as of the given array.</span><br>
Syntax:<br>
np.zeros_like(array,dtype)

In [67]:
#array
a

array([21, 52, 93])

In [68]:
#creating a zeros array, form array a
z = np.zeros_like(a)

In [69]:
z

array([0, 0, 0])

In [70]:
#creating a 2-D Random array of shape 5x2
z1 = np.random.random((5,2))

In [71]:
z1

array([[0.34491935, 0.33592365],
       [0.50935363, 0.41044537],
       [0.36059374, 0.964276  ],
       [0.18952063, 0.31526386],
       [0.14344684, 0.13485044]])

In [72]:
#creating a zeros array, from array z1
u = np.zeros_like(z1)

In [73]:
u

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

---

<span style ='font-size:medium'>Full Like Array- It returns a array of constant element with the same shape & type as of the given array.</span><br>
Syntax:<br>
np.full_like(array, fill_value,dtype)

In [74]:
#array
a

array([21, 52, 93])

In [75]:
#creating a full array of 7, from array a
y = np.full_like(a,7)

In [76]:
y

array([7, 7, 7])

In [77]:
#creating a 3-D Random arrray of shape 2x3x4
y1 = np.random.random((2,3,4))

In [78]:
y1

array([[[0.87586274, 0.41900288, 0.46494338, 0.63998166],
        [0.8447403 , 0.84928397, 0.85172661, 0.64191014],
        [0.74510505, 0.58022417, 0.02710296, 0.93060056]],

       [[0.23640768, 0.45664301, 0.9400139 , 0.77842029],
        [0.26688142, 0.58464407, 0.17095513, 0.1359986 ],
        [0.7862607 , 0.2527392 , 0.72591741, 0.25303431]]])

In [79]:
#creating a full array of 71 from array y1
np.full_like(y1,71)

array([[[71., 71., 71., 71.],
        [71., 71., 71., 71.],
        [71., 71., 71., 71.]],

       [[71., 71., 71., 71.],
        [71., 71., 71., 71.],
        [71., 71., 71., 71.]]])

In [80]:
#creating a full array -71 of integer datatype, from array y1
np.full_like(y1,-71,dtype=int)

array([[[-71, -71, -71, -71],
        [-71, -71, -71, -71],
        [-71, -71, -71, -71]],

       [[-71, -71, -71, -71],
        [-71, -71, -71, -71],
        [-71, -71, -71, -71]]])