<span style="font-size:larger ; background-color:#333333; color:white">Numpy - Zeros Array</span>

<span style="font-size:medium; background-color:#333333; color:white">ZA = np.zeros(shape, dtype)</span>

<span style="font-size:small; background-color:#333333; color:white">
- We can define the shape and data-type of zeros array..<br>
- We can create 1-D, 2-D, as well as 3-D zeros array.<br>
- The default data-type is float.
</span>


In [6]:
import numpy as np

In [7]:
# Create a zeros array of 1 dimension.
Z1 = np.zeros(3)    
Z1

array([0., 0., 0.])

In [8]:
#Create a zeros array of 1 dimension with data type as intgeger.
Z2 = np.zeros(15, dtype = int)
Z2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
#check the type.
type(Z2)

numpy.ndarray

In [10]:
#check the dimension.
np.ndim(Z2)

1

In [11]:
#create a zeros array of 2 dimensions
Z3 = np.zeros((3,4))
Z3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
#create a zeros arrayof 2 dimensions.
Z4 = np.zeros((3,4), dtype=int)
Z4

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [13]:
#check the shape 
Z4.shape

(3, 4)

In [14]:
#create a zeros array of 3 dimensions.
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [15]:
#create a zeros array of 3 dimensions with data type as integer.
Z5 = np.zeros((3,3,3), dtype=int)
Z5

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [16]:
#check the dimensions
Z5.ndim

3

In [17]:
#check the size 
Z5.size

27